version: '3.8'

services:
  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9090"
    container_name: minio
    volumes:
      - ~/minio/data:/data
    environment:
      - "MINIO_ROOT_USER=root"
      - "MINIO_ROOT_PASSWORD=rootpass"

    
