version: '3.8'

services:
  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9080"
    container_name: minio
    ports:
      - "9000:9000"
      - "9080:9080"
    volumes:
      - ~/minio/data:/data
    environment:
      - "MINIO_ROOT_USER=root"
      - "MINIO_ROOT_PASSWORD=rootpass"

    
